#!/bin/bash
echo "=== Jarvis-Private Startup Check ==="
echo ""
echo "1. Identity files:"
[ -f CLAUDE.md ] && echo "   CLAUDE.md ✅" || echo "   CLAUDE.md ❌"
[ -f AGENTS.md ] && echo "   AGENTS.md ✅" || echo "   AGENTS.md ❌"
echo ""
echo "2. Swarm infra:"
[ -f workspaces/Co-op/SWARM.md ] && echo "   SWARM.md ✅" || echo "   SWARM.md ❌"
[ -f workspaces/Co-op/lilith_task_sender.py ] && echo "   task_sender ✅" || echo "   task_sender ❌"
echo ""
echo "3. MARCO-POLO:"
ls workspaces/Co-op/MARCO-POLO/MP-*.md 2>/dev/null | head -2 && echo "   logs ✅" || echo "   no logs"
echo ""
echo "=== Ready ==="
