#!/usr/bin/env node
import http from "node:http";
import {createGaiaOSBridgeClient,GAIAOS_TOOL_ALLOWLIST} from "./client.mjs";
const host=process.env.RAVENOS_GAIA_BRIDGE_BIND||"0.0.0.0";const port=Number(process.env.PORT||8787);const gatewayToken=process.env.RAVENOS_GAIA_BRIDGE_TOKEN||"";
function send(res,status,body){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-ravenos-gaiaos-bridge":"0.2.0"});res.end(JSON.stringify(body,null,2));}
function authorized(req){return !gatewayToken||req.headers.authorization===`Bearer ${gatewayToken}`;}
async function readJson(req){const chunks=[];let total=0;for await(const chunk of req){total+=chunk.length;if(total>65536)throw new Error("request body too large");chunks.push(chunk);}if(!chunks.length)return{};return JSON.parse(Buffer.concat(chunks).toString("utf8"));}
function compactTool(tool){return{name:tool?.name,title:tool?.title??null,description:tool?.description??null,inputSchema:tool?.inputSchema??null};}
function wrapped(result,extra={}){return{bridge:"RavenOS/GaiaOSBridge",bridge_version:"0.2.0",authority_boundary:"NAOMI",read_only:true,...extra,result:result.value};}
const server=http.createServer(async(req,res)=>{try{if(!authorized(req))return send(res,401,{error:"unauthorized"});const url=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);const client=createGaiaOSBridgeClient({timeoutMs:30000});
if(req.method==="GET"&&url.pathname==="/health"){const info=await client.initialize();const tools=await client.listTools();const names=(tools?.tools||[]).map(t=>t.name).sort();const missing=GAIAOS_TOOL_ALLOWLIST.filter(n=>!names.includes(n));return send(res,missing.length?503:200,{status:missing.length?"degraded":"ok",bridge:"RavenOS/GaiaOSBridge",bridge_version:"0.2.0",remote_mcp:client.url,remote_server:info,authority_boundary:"NAOMI",read_only:true,tools_discovered:names,missing_expected_tools:missing});}
if(req.method==="GET"&&url.pathname==="/gaiaos/tools"){const tools=await client.listTools();return send(res,200,{bridge:"RavenOS/GaiaOSBridge",bridge_version:"0.2.0",authority_boundary:"NAOMI",tools:(tools?.tools||[]).filter(t=>GAIAOS_TOOL_ALLOWLIST.includes(t.name)).map(compactTool)});}
if(req.method==="GET"&&url.pathname==="/gaiaos/selftest")return send(res,200,wrapped(await client.selftest(),{tool:"gaia_selftest"}));
if(req.method==="POST"&&url.pathname==="/gaiaos"){const b=await readJson(req);const request=String(b.request||"").trim();if(!request)return send(res,422,{error:"request is required"});return send(res,200,wrapped(await client.gaia(request,Array.isArray(b.requested_members)?b.requested_members:[],Number(b.max_members||3),b.include_context!==false,Number(b.context_limit||6),Number(b.context_depth||1)),{tool:"gaia"}));}
if(req.method==="POST"&&url.pathname==="/gaiaos/call"){const b=await readJson(req);const name=String(b.name||"");if(!GAIAOS_TOOL_ALLOWLIST.includes(name))return send(res,400,{error:"tool_not_allowed",name,allowlist:GAIAOS_TOOL_ALLOWLIST});return send(res,200,wrapped(await client.callTool(name,b.arguments||{}),{tool:name}));}
if(req.method==="POST"&&url.pathname==="/gaiaos/dispatch"){const b=await readJson(req);if(!Array.isArray(b.signals)||!b.signals.length)return send(res,422,{error:"signals must be a non-empty array"});return send(res,200,wrapped(await client.dispatch(b.signals,Array.isArray(b.requested_members)?b.requested_members:[],Number(b.max_members||3)),{tool:"gaia_dispatch"}));}
if(req.method==="POST"&&url.pathname==="/gaiaos/context"){const b=await readJson(req);const subject=String(b.subject||"").trim();if(!subject)return send(res,422,{error:"subject is required"});return send(res,200,wrapped(await client.context(subject,Number(b.limit||10),Number(b.depth||1)),{tool:"gaia_context"}));}
return send(res,404,{error:"not_found",routes:["GET /health","GET /gaiaos/tools","GET /gaiaos/selftest","POST /gaiaos","POST /gaiaos/call","POST /gaiaos/dispatch","POST /gaiaos/context"]});}catch(error){return send(res,502,{error:"gaiaos_bridge_error",message:error?.message||String(error)});}});
server.listen(port,host,()=>{console.log(`RavenOS GaiaOSBridge listening on http://${host}:${port}`);console.log("Authority boundary: NAOMI");});
