import {EventBus,aegisGate} from './core/event-bus.js';
import {Router} from './core/router.js';
import {ObserverStore} from './core/observer-store.js';
import {menuScreen,legacyScreen} from './screens/menu.js';
import {createOmniScreen} from './screens/omni-room.js';
import {bridgeScreen,intelligenceScreen,mnemosScreen,telemetryScreen,godFieldScreen,fleetScreen,shipMapScreen} from './screens/vessel-systems.js';

const root=document.getElementById('screen-inner');
const led=document.getElementById('field-led');
const net=document.getElementById('net-state');
const bus=new EventBus({gate:aegisGate,sink:event=>console.debug('[VESSEL BUS]',event)});
const store=new ObserverStore({bus,led,net});
const router=new Router({root,bus});
router.store=store;
router.register('menu',menuScreen);
router.register('legacy',legacyScreen);
router.register('omni',createOmniScreen({store,bus}));
router.register('bridge',bridgeScreen);
router.register('intelligence',intelligenceScreen);
router.register('mnemos',mnemosScreen);
router.register('telemetry',telemetryScreen);
router.register('godfield',godFieldScreen);
router.register('fleet',fleetScreen);
router.register('shipmap',shipMapScreen);
document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>router.command(button.dataset.command)));
window.addEventListener('keydown',event=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Enter:'confirm',Escape:'back'};if(map[event.key]){event.preventDefault();router.command(map[event.key]);}});
window.addEventListener('online',()=>store.load().then(()=>router.render()).catch(()=>{}));
window.addEventListener('offline',()=>store.setState(false));
let installPrompt=null;
const installButton=document.getElementById('install-app');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.hidden=false;});
installButton.addEventListener('click',async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;installButton.hidden=true;});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(error=>bus.emit('service_worker_failed',{error:String(error)}));
bus.on('omni_snapshot_loaded',({data})=>console.info('OMNI observer snapshot ready',data));
router.go('menu');
store.load().then(()=>router.render()).catch(()=>router.render());