#!/usr/bin/env python3
"""
JARVIS patch register — the one consistent, chronological patch system.

A patch is any unit of change worth tracing. It gets a monotonic ID (P35,
P36, ...) the moment it is OPENED, in chronological order. While a patch is
OPEN you keep BUILDING it — every change appends a timestamped entry — until
you EXECUTE it (ship/deploy). The record is the audit trail: open -> entries
-> execute, all dated.

Source of truth: audit/patch_ledger.json (this tool is the only writer).
Derived cache: logs/patch-log.json (regenerated on every write).

Lifecycle (the `status` field is the canonical lifecycle):
  open      building — accumulating entries before execution
  executed  shipped / deployed (terminal success)
  partial   executed but carrying `remaining` items (still open for those)
  pending   reserved, not started
  deferred  held by decision (not rejected)
  reference read-only advisory, never executed

Usage:
  jarvis-patch.py open  "<title>" [priority]      open the next chronological patch
  jarvis-patch.py add   <Pxx> "<change>" [SHA]    append a timestamped build entry
  jarvis-patch.py exec  <Pxx> ["<note>"] [SHA...]  mark executed + stamp deploy time
  jarvis-patch.py defer <Pxx> ["<reason>"]         hold the patch (not rejected)
  jarvis-patch.py show  <Pxx>                       print one patch in full
  jarvis-patch.py list                              open + building + pending patches
No args -> list.
"""
import json
import os
import sys
from datetime import datetime, timezone

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LEDGER_PATH = os.path.join(REPO_ROOT, "audit", "patch_ledger.json")
CACHE_PATH = os.path.join(REPO_ROOT, "logs", "patch-log.json")

OPEN_STATES = ("open", "partial", "pending")


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load() -> dict:
    with open(LEDGER_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def dumps_ledger(ledger: dict) -> str:
    """Compact one-line-per-patch JSON — keeps diffs to a single line per change."""
    head_keys = [k for k in ledger if k not in ("patches", "implementation_order")]
    out = ["{"]
    for k in head_keys:
        out.append(f"  {json.dumps(k)}: {json.dumps(ledger[k], ensure_ascii=False)},")
    out.append('  "patches": [')
    patches = ledger.get("patches", [])
    for i, p in enumerate(patches):
        comma = "," if i < len(patches) - 1 else ""
        out.append("    " + json.dumps(p, ensure_ascii=False, separators=(",", ":")) + comma)
    if "implementation_order" in ledger:
        out.append("  ],")
        order = ledger["implementation_order"]
        out.append('  "implementation_order": [')
        for i, item in enumerate(order):
            comma = "," if i < len(order) - 1 else ""
            out.append("    " + json.dumps(item, ensure_ascii=False) + comma)
        out.append("  ]")
    else:
        out.append("  ]")
    out.append("}")
    return "\n".join(out) + "\n"


def save(ledger: dict) -> None:
    ledger["last_updated"] = now_iso()
    with open(LEDGER_PATH, "w", encoding="utf-8") as f:
        f.write(dumps_ledger(ledger))
    _write_cache(ledger)


def _write_cache(ledger: dict) -> None:
    """Regenerate the legacy derived cache from the canonical ledger (one writer)."""
    try:
        cache = {
            "version": "2.1",
            "last_updated": ledger["last_updated"],
            "authority": ledger.get("authority", "Raven (John Barber)"),
            "derived_from": "audit/patch_ledger.json",
            "note": "DERIVED — do not edit by hand. Regenerated by scripts/jarvis-patch.py.",
            "patches": {
                p["id"]: {"status": p.get("status", ""), "summary": p.get("summary", "")}
                for p in ledger.get("patches", [])
            },
        }
        os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
        with open(CACHE_PATH, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
            f.write("\n")
    except Exception as e:  # cache is best-effort; canonical write already succeeded
        print(f"  (cache regen skipped: {e})", file=sys.stderr)


def find(ledger: dict, pid: str) -> dict | None:
    pid = pid.upper()
    for p in ledger.get("patches", []):
        if p.get("id", "").upper() == pid:
            return p
    return None


def next_id(ledger: dict) -> str:
    declared = ledger.get("next_patch")
    nums = [int(p["id"][1:]) for p in ledger.get("patches", []) if p.get("id", "").startswith("P")]
    computed = f"P{(max(nums) + 1) if nums else 0:02d}"
    # honor next_patch unless a higher id already exists (chronological integrity)
    if declared and int(declared[1:]) > (max(nums) if nums else -1):
        return declared
    return computed


# ── commands ────────────────────────────────────────────────────────────────

def cmd_open(args: list) -> None:
    if not args:
        sys.exit("usage: open \"<title>\" [priority]")
    title = args[0]
    priority = args[1] if len(args) > 1 else "normal"
    ledger = load()
    pid = next_id(ledger)
    patch = {
        "id": pid,
        "name": f"Patch {int(pid[1:])} — {title}",
        "priority": priority,
        "status": "open",
        "summary": title,
        "opened_at": now_iso(),
        "commits": [],
        "entries": [],
    }
    ledger.setdefault("patches", []).append(patch)
    ledger["next_patch"] = f"P{int(pid[1:]) + 1:02d}"
    ledger["intake_max_patch"] = pid
    save(ledger)
    print(f"OPENED {pid} (open · {priority}) — {title}")
    print(f"  build it: jarvis-patch.py add {pid} \"<change>\"")
    print(f"  ship it:  jarvis-patch.py exec {pid} \"<note>\" <sha>")


def cmd_add(args: list) -> None:
    if len(args) < 2:
        sys.exit("usage: add <Pxx> \"<change>\" [SHA]")
    pid, note = args[0], args[1]
    sha = args[2] if len(args) > 2 else None
    ledger = load()
    patch = find(ledger, pid)
    if not patch:
        sys.exit(f"no such patch: {pid}")
    if patch.get("status") not in OPEN_STATES:
        sys.exit(f"{pid} is '{patch.get('status')}' — not open for building. Re-open by editing the ledger if intended.")
    entry = {"ts": now_iso(), "note": note}
    if sha:
        entry["commit"] = sha
        patch.setdefault("commits", []).append(sha)
    patch.setdefault("entries", []).append(entry)
    save(ledger)
    n = len(patch["entries"])
    print(f"+ {pid} entry #{n}: {note}" + (f"  [{sha}]" if sha else ""))


def cmd_exec(args: list) -> None:
    if not args:
        sys.exit("usage: exec <Pxx> [\"<note>\"] [SHA...]")
    pid = args[0]
    rest = args[1:]
    note = None
    shas = []
    for a in rest:
        # a token that looks like a commit sha (hex, 7-40) is a commit; else the note
        if all(c in "0123456789abcdef" for c in a.lower()) and 7 <= len(a) <= 40:
            shas.append(a)
        elif note is None:
            note = a
        else:
            shas.append(a)
    ledger = load()
    patch = find(ledger, pid)
    if not patch:
        sys.exit(f"no such patch: {pid}")
    ts = now_iso()
    patch["status"] = "executed"
    patch["deployed_at"] = ts[:10]
    for s in shas:
        if s not in patch.setdefault("commits", []):
            patch["commits"].append(s)
    entry = {"ts": ts, "note": note or "executed", "executed": True}
    if shas:
        entry["commit"] = shas[-1]
    patch.setdefault("entries", []).append(entry)
    save(ledger)
    print(f"EXECUTED {pid} @ {patch['deployed_at']}" + (f" — {note}" if note else "")
          + (f"  commits: {', '.join(shas)}" if shas else ""))


def cmd_defer(args: list) -> None:
    if not args:
        sys.exit("usage: defer <Pxx> [\"<reason>\"]")
    pid = args[0]
    reason = args[1] if len(args) > 1 else "deferred"
    ledger = load()
    patch = find(ledger, pid)
    if not patch:
        sys.exit(f"no such patch: {pid}")
    patch["status"] = "deferred"
    patch.setdefault("entries", []).append({"ts": now_iso(), "note": f"DEFERRED — {reason}"})
    save(ledger)
    print(f"DEFERRED {pid} — {reason}")


def _fmt_patch(p: dict) -> str:
    head = f"{p['id']} [{p.get('status','?')}·{p.get('priority','?')}] {p.get('summary', p.get('name',''))}"
    lines = [head]
    if p.get("opened_at"):
        lines.append(f"  opened:   {p['opened_at']}")
    if p.get("deployed_at"):
        lines.append(f"  deployed: {p['deployed_at']}")
    if p.get("commits"):
        lines.append(f"  commits:  {', '.join(p['commits'])}")
    for e in p.get("entries", []):
        mark = "✓" if e.get("executed") else "·"
        sha = f"  [{e['commit']}]" if e.get("commit") else ""
        lines.append(f"  {mark} {e['ts'][:16].replace('T',' ')}  {e['note']}{sha}")
    for r in p.get("remaining", []):
        lines.append(f"  ▸ remaining: {r}")
    return "\n".join(lines)


def cmd_show(args: list) -> None:
    if not args:
        sys.exit("usage: show <Pxx>")
    ledger = load()
    patch = find(ledger, args[0])
    if not patch:
        sys.exit(f"no such patch: {args[0]}")
    print(_fmt_patch(patch))


def cmd_list(_args: list) -> None:
    ledger = load()
    patches = ledger.get("patches", [])
    opening = [p for p in patches if p.get("status") == "open"]
    building = [p for p in patches if p.get("status") == "partial"]
    pending = [p for p in patches if p.get("status") == "pending"]
    print(f"PATCH REGISTER — next id {ledger.get('next_patch','?')}  (canonical: audit/patch_ledger.json)")
    if opening:
        print("\nOPEN (building — accumulating before execution):")
        for p in opening:
            n = len(p.get("entries", []))
            last = p["entries"][-1]["note"] if p.get("entries") else "no entries yet"
            print(f"  ● {p['id']} ({n} entr{'y' if n==1 else 'ies'}) {p.get('summary','')} — last: {last[:60]}")
    if building:
        print("\nPARTIAL (executed, carrying remaining items):")
        for p in building:
            print(f"  ◐ {p['id']} {p.get('summary','')[:70]}")
    if pending:
        print("\nPENDING (reserved, not started):")
        for p in pending:
            print(f"  ○ {p['id']} {p.get('summary','')[:70]}")


COMMANDS = {
    "open": cmd_open, "add": cmd_add, "exec": cmd_exec, "execute": cmd_exec,
    "defer": cmd_defer, "show": cmd_show, "list": cmd_list,
}


def main() -> None:
    argv = sys.argv[1:]
    if not argv:
        cmd_list([])
        return
    cmd, rest = argv[0], argv[1:]
    fn = COMMANDS.get(cmd)
    if not fn:
        sys.exit(f"unknown command '{cmd}'. one of: {', '.join(sorted(set(COMMANDS)))}")
    fn(rest)


if __name__ == "__main__":
    main()
