#!/usr/bin/env python3
"""Generate the Jarvis MCP runtime registry and legacy database mirror sync."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

VERSION = "0.11.35"
REPO_ROOT = Path(__file__).resolve().parents[2]
FUNCTION_ROOT = REPO_ROOT / "core/supabase/functions/jarvis-mcp"
TS_OUTPUT = FUNCTION_ROOT / "tool-registry.generated.ts"
SQL_OUTPUT = REPO_ROOT / "operations/sql/mcp-tool-registry-sync.sql"
REGISTER_RE = re.compile(r"""registerTool\s*\(\s*["'`]([^"'`]+)["'`]""")


def registrations() -> list[tuple[str, str]]:
    paths = [FUNCTION_ROOT / "index.ts", FUNCTION_ROOT / "resources.ts"]
    paths.extend(sorted((FUNCTION_ROOT / "tools").glob("*.ts")))
    found: list[tuple[str, str]] = []
    for path in paths:
        for name in REGISTER_RE.findall(path.read_text(encoding="utf-8")):
            found.append((name, path.relative_to(FUNCTION_ROOT).as_posix()))
    names = [name for name, _ in found]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SystemExit(f"duplicate MCP registrations: {', '.join(duplicates)}")
    return sorted(found)


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_ts(rows: list[tuple[str, str]]) -> str:
    lines = [
        "// GENERATED by operations/scripts/build_mcp_tool_registry.py. DO NOT EDIT.",
        "// Runtime registrations in index.ts, resources.ts, and tools/*.ts are the source of truth.",
        "",
        f"export const JARVIS_MCP_VERSION = {quote(VERSION)};",
        "",
        "export const TOOL_NAMES = [",
        *(f"  {quote(name)}," for name, _ in rows),
        "] as const;",
        "",
        "export const TOOL_SOURCES: Readonly<Record<string, string>> = {",
        *(f"  {quote(name)}: {quote(source)}," for name, source in rows),
        "};",
        "",
        "export const TOOL_COUNT = TOOL_NAMES.length;",
        "",
    ]
    return "\n".join(lines)


def values_sql(rows: list[tuple[str, str]]) -> list[str]:
    return [f"  ({sql_quote(name)}, {sql_quote(source)})" for name, source in rows]


def array_sql(rows: list[tuple[str, str]]) -> list[str]:
    return [f"    {sql_quote(name)}" for name, _ in rows]


def render_sql(rows: list[tuple[str, str]]) -> str:
    values = ",\n".join(values_sql(rows))
    names = ",\n".join(array_sql(rows))
    return f"""-- GENERATED by operations/scripts/build_mcp_tool_registry.py. DO NOT EDIT.
-- Reconciles legacy database mirrors with the registrations in the deployed Jarvis MCP source.
begin;

with current_tools(name, source_path) as (
values
{values}
)
insert into public.jarvis_mcp_manifest (name, description, input_schema, updated_at)
select name, 'Registered Jarvis MCP tool; source: ' || source_path, '{{"type":"object"}}'::jsonb, timezone('utc', now())
from current_tools
on conflict (name) do update
set description = excluded.description,
    input_schema = excluded.input_schema,
    updated_at = excluded.updated_at;

delete from public.jarvis_mcp_manifest
where name <> all (array[
{names}
]::text[]);

with current_tools(name, source_path) as (
values
{values}
)
insert into public.mcp_tool_definitions (tool_name, description, input_schema, is_active)
select name, 'Registered Jarvis MCP tool; source: ' || source_path, '{{"type":"object"}}'::jsonb, true
from current_tools
on conflict (tool_name) do update
set description = excluded.description,
    input_schema = excluded.input_schema,
    is_active = true;

update public.mcp_tool_definitions
set is_active = false
where tool_name <> all (array[
{names}
]::text[]);

commit;
"""


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return True
    if check:
        print(f"stale generated artifact: {path.relative_to(REPO_ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = registrations()
    ok = write_or_check(TS_OUTPUT, render_ts(rows), args.check)
    ok = write_or_check(SQL_OUTPUT, render_sql(rows), args.check) and ok
    print(f"Jarvis MCP registry: {len(rows)} tools; version {VERSION}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
