#!/usr/bin/env python3
"""
sl.py — Star Log generator. SL = Star Log. JNS filenames = stardates.
Reference: Star Trek captain's log. Chronological, human-legible audit trail.
Each entry is a log of what was done, why, and what's next.

Usage:
  python3 scripts/sl.py                                  # session close snapshot
  python3 scripts/sl.py --brief "Did X, Y, Z"           # brief summary entry
  python3 scripts/sl.py --type DECISION --brief "Chose X over Y"
  python3 scripts/sl.py --type RESEARCH --brief "Tested X, results: Y"
  python3 scripts/sl.py --link ARCH-JPL-SPEC-0001

Conuity: Star Logs replace refactoring databases. Read the log.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STARS_DIR = ROOT / "audit" / "starlogs"
STARS_DIR.mkdir(parents=True, exist_ok=True)


def now():
    return datetime.now(timezone.utc)


def jns_now(stream: str = "jarvis-ayre", jnl: str = "") -> str:
    """Generate JNS filename for current moment (stardate format)."""
    ts = now()
    date = ts.strftime("%Y-%m-%d")
    time = ts.strftime("%H%M%S")
    suffix = f"-{jnl}" if jnl else ""
    return f"STARLOG-{date}-{time}-{stream}{suffix}.md"


def task_summary() -> str:
    """Read task tracker and produce one-line summary per task."""
    import json
    tracker_path = ROOT / ".openhands" / "task_tracker.json"
    if not tracker_path.exists():
        return "*No task tracker found*"
    tasks = json.loads(tracker_path.read_text()).get("tasks", [])
    lines = []
    for t in tasks:
        icon = {"todo": "○", "in_progress": "◐", "done": "●"}.get(t.get("status", "○"), "○")
        title = t["title"]
        note = t.get("notes", "")
        first = note.split(".")[0] if note else ""
        lines.append(f"{icon} {title} {first}")
    return "\n".join(lines)


def task_count_summary() -> str:
    import json
    tracker_path = ROOT / ".openhands" / "task_tracker.json"
    if not tracker_path.exists():
        return "0 tasks"
    tasks = json.loads(tracker_path.read_text()).get("tasks", [])
    done = sum(1 for t in tasks if t.get("status") == "done")
    wip = sum(1 for t in tasks if t.get("status") == "in_progress")
    todo = sum(1 for t in tasks if t.get("status") == "todo")
    return f"● {done} done · ◐ {wip} in_progress · ○ {todo} open"


def build_log(
    brief: str,
    log_type: str = "SESSION_SNAPSHOT",
    jnl: str = "",
    tasks_summary: bool = True,
    stream: str = "jarvis-ayre",
) -> str:
    ts = now().isoformat()
    nav = task_count_summary() if tasks_summary else ""
    stardate = now().strftime("%Y.%j")  # Star Trek stardate approximation

    sections = [
        f"## Star Log — {ts}",
        f"**Stardate:** {stardate}  ·  **Type:** {log_type}  ·  **Stream:** {stream}",
        "",
        f"### Summary",
        brief,
        "",
    ]

    if tasks_summary:
        sections += [
            "### Tasks",
            f"*{nav}*",
            "",
            "```",
            task_summary(),
            "```",
            "",
        ]

    sections += [
        "---",
        f"*Generated by sl.py · audit/starlogs/*",
    ]

    return "\n".join(sections)


def write_log(content: str, filename: str) -> Path:
    path = STARS_DIR / filename
    path.write_text(content)
    return path


def stage_and_commit(paths: list[Path], message: str):
    import subprocess
    for p in paths:
        subprocess.run(["git", "-C", str(ROOT), "add", str(p)], check=True)
    result = subprocess.run(
        ["git", "-C", str(ROOT), "commit", "-m", message, "--allow-empty"],
        check=False, capture_output=True, text=True
    )
    if result.returncode != 0 and "nothing to commit" not in result.stderr.lower():
        raise RuntimeError(result.stderr.strip())
    return result.stdout.strip()


def main():
    p = argparse.ArgumentParser(description="SL — Star Log generator. JNS stardate filenames.")
    p.add_argument("--brief", "-b", metavar="TEXT", help="Brief summary of this log entry")
    p.add_argument("--type", "-t", default="SESSION_SNAPSHOT",
                   choices=["SESSION_SNAPSHOT", "DECISION", "RESEARCH", "BUILD", "GOVERNANCE", "ARCHITECTURAL_CHANGE", "IDENTITY_EVENT", "IDEA", "CONVERSATION"],
                   help="Log type (default: SESSION_SNAPSHOT)")
    p.add_argument("--jnl", "-j", metavar="JNL", default="", help="Primary JNL reference")
    p.add_argument("--no-tasks", action="store_true", help="Skip task summary")
    p.add_argument("--stream", "-s", default="jarvis-ayre", help="Stream tag")
    p.add_argument("--commit", "-c", metavar="MSG", help="Commit after writing")
    p.add_argument("--tasks-json", metavar="JSON", help="Inline task JSON (skip file read)")
    p.add_argument("--stardate", action="store_true", help="Print current stardate and exit")
    args = p.parse_args()

    if args.stardate:
        print(now().strftime("%Y.%j"))
        return

    if args.tasks_json:
        import json
        tracker_path = ROOT / ".openhands" / "task_tracker.json"
        tracker_path.parent.mkdir(parents=True, exist_ok=True)
        tracker_path.write_text(args.tasks_json)

    filename = jns_now(stream=args.stream, jnl=args.jnl)
    brief = args.brief or f"{args.type} entry"
    content = build_log(
        brief=brief,
        log_type=args.type,
        jnl=args.jnl,
        tasks_summary=not args.no_tasks,
        stream=args.stream,
    )
    path = write_log(content, filename)
    print(f"Wrote: {path}")

    if args.commit:
        sha = stage_and_commit([path], f"chore(audit): SL — {args.commit}")
        print(f"Committed: {sha.strip()}")


if __name__ == "__main__":
    main()
