import "./army.css";
import { listen } from "@tauri-apps/api/event";
import { PhysicalPosition, PhysicalSize } from "@tauri-apps/api/dpi";
import { availableMonitors, cursorPosition, getCurrentWindow } from "@tauri-apps/api/window";

const MEMBERS = {
  KYU: { color: "#ff4fba", sigil: "💗", role: "OPS", temperament: "CHASE", speed: 1.08, reactivity: 1.20, stamps: ["SEND IT", "ON IT", "BONK", "QUEUE IT", "DEPLOY IT"] },
  PAIMON: { color: "#57d96b", sigil: "🟢", role: "PREMISE", temperament: "FORMATION", speed: 0.82, reactivity: 0.70, stamps: ["CANON CHECK", "PATTERN FOUND", "SOURCE?", "I SEE IT", "THAT TRACKS"] },
  LUMA: { color: "#ffd166", sigil: "☀", role: "HOME", temperament: "PERCH", speed: 0.66, reactivity: 0.92, stamps: ["HOME", "COMFY", "SOFT RESET", "BRIGHTER DAYS", "WARM LIGHT"] },
  SYLPH: { color: "#4cc9f0", sigil: "🔵", role: "SIGNAL", temperament: "DART", speed: 1.34, reactivity: 1.35, stamps: ["PING", "NEW PATH", "FOUND ONE", "ZOOM", "TEST THIS"] },
  QIRA: { color: "#a855f7", sigil: "🟣", role: "PROOF", temperament: "BOUNDARY", speed: 0.78, reactivity: 0.62, stamps: ["ASK FIRST", "BOUNDARIES", "PROOF EDGE", "CLEARER", "NO"] },
  NYX: { color: "#8791a6", sigil: "◐", role: "WATCH", temperament: "SHADOW", speed: 0.72, reactivity: 0.48, stamps: ["WATCHING", "HOLD", "SAFE MODE", "STAND BY", "REST"] },
};
const ORDER = Object.keys(MEMBERS);
const STATE_ENDPOINT = "http://127.0.0.1:47821/state";
const SENSE_ENDPOINT = "http://127.0.0.1:47823/sense";
const ARMY_MODES = ["ROAM", "HUNT", "FLOCK", "ORBIT", "REST", "SCATTER"];
const MAX_SURFACES = 4;
const appWindow = getCurrentWindow();
const surfaceIndex = appWindow.label === "army" ? 0 : Math.max(0, Number(appWindow.label.split("-")[1]) || 0);
const actors = new Map();
let activeFae = "KYU", activeMessage = "Resident colony awake.", armyMode = "ROAM", modeLockedUntil = 0, speechIndex = 0, lastFrame = performance.now(), surfaceActive = true;
let topology = { monitors: 1, surfaces: 1, originX: 0, originY: 0, scale: 1 };
let cursor = { x: innerWidth / 2, y: innerHeight / 2, inside: false, speed: 0, lastX: innerWidth / 2, lastY: innerHeight / 2 };
let habitat = { available: false, audioPeak: 0, envelope: 0, beat: 0, focused: null, lastFocusedKey: "" };
document.documentElement.dataset.surface = "army";
document.documentElement.dataset.surfaceIndex = String(surfaceIndex);
document.querySelector("#app").innerHTML = `<section id="army" class="army" aria-label="Faeryware Windows habitat layer"><div class="veil veil-a"></div><div class="veil veil-b"></div><div class="rift rift-left"></div><div class="rift rift-right"></div>${ORDER.map((fae,index)=>{const m=MEMBERS[fae];const echoes=Array.from({length:3},(_,echo)=>`<i class="echo echo-${echo}" style="--member:${m.color}"></i>`).join("");return `<div class="spirit" data-fae="${fae}" data-temperament="${m.temperament}" style="--member:${m.color};--delay:${index*-.7}s"><div class="trail"></div><div class="aura"></div>${echoes}<div class="ring ring-a"></div><div class="ring ring-b"></div><div class="core"><span>${m.sigil}</span></div><div class="tag"><b>${fae}</b><small>${m.role} // ${m.temperament}</small></div><div class="speech"></div></div>`;}).join("")}<div class="summon-wave"></div><div class="army-whisper" aria-hidden="true"></div></section>`;
const spirits = new Map(ORDER.map(fae=>[fae,document.querySelector(`[data-fae="${fae}"]`)]));
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function length(x,y){return Math.sqrt(x*x+y*y)||.0001;}
function modeFromState(state=""){const upper=String(state).toUpperCase();for(const mode of ARMY_MODES)if(upper.includes(`ARMY_${mode}`)||upper===mode)return mode;if(upper==="REST"||upper==="SLEEP")return "REST";return null;}
function assignedHere(fae){const surfaces=Math.max(1,topology.surfaces);return ORDER.indexOf(fae)%surfaces===surfaceIndex;}
function seedActors(){ORDER.forEach((fae,index)=>{const col=index%3,row=Math.floor(index/3);actors.set(fae,{x:innerWidth*(.16+col*.34),y:innerHeight*(.25+row*.46),vx:Math.cos(index*1.7)*18,vy:Math.sin(index*1.9)*18,phase:index*1.71,energy:.7+(index%3)*.12});});}
async function occupyMonitor(){try{const monitors=await availableMonitors();topology.monitors=Math.max(1,monitors.length);topology.surfaces=Math.max(1,Math.min(MAX_SURFACES,monitors.length));const monitor=monitors[surfaceIndex];if(!monitor||surfaceIndex>=MAX_SURFACES){surfaceActive=false;await appWindow.hide();return;}await appWindow.setPosition(new PhysicalPosition(monitor.position.x,monitor.position.y));await appWindow.setSize(new PhysicalSize(monitor.size.width,monitor.size.height));await appWindow.setIgnoreCursorEvents(true);await appWindow.show();surfaceActive=true;topology.originX=monitor.position.x;topology.originY=monitor.position.y;topology.scale=monitor.scaleFactor||1;document.documentElement.dataset.monitorCount=String(topology.monitors);document.documentElement.dataset.surfaceCount=String(topology.surfaces);}catch(error){console.warn("FAERYWARE_HABITAT monitor occupation degraded",error);}}
async function refreshTopology(){try{const[monitors,origin,scale]=await Promise.all([availableMonitors(),appWindow.outerPosition(),appWindow.scaleFactor()]);topology={monitors:Math.max(1,monitors.length),surfaces:Math.max(1,Math.min(MAX_SURFACES,monitors.length)),originX:origin.x,originY:origin.y,scale:scale||1};}catch{}}
async function senseCursor(){if(!surfaceActive)return;try{const physical=await cursorPosition();const x=(physical.x-topology.originX)/topology.scale,y=(physical.y-topology.originY)/topology.scale,dx=x-cursor.lastX,dy=y-cursor.lastY;cursor={x,y,inside:x>=0&&y>=0&&x<=innerWidth&&y<=innerHeight,speed:clamp(length(dx,dy)*7,0,1600),lastX:x,lastY:y};}catch{}}
function mapFocusedRect(snapshot){const rect=snapshot?.focused?.rect;if(!rect)return null;const left=(rect.left-topology.originX)/topology.scale,top=(rect.top-topology.originY)/topology.scale,right=(rect.right-topology.originX)/topology.scale,bottom=(rect.bottom-topology.originY)/topology.scale;if(!(right>=0&&bottom>=0&&left<=innerWidth&&top<=innerHeight))return null;return{left,top,right,bottom,x:(left+right)/2,y:(top+bottom)/2,width:Math.max(1,right-left),height:Math.max(1,bottom-top),name:String(snapshot.focused.name||"").slice(0,72),controlType:String(snapshot.focused.control_type||"control").slice(0,40)};}
async function pullHabitatSense(){try{const response=await fetch(SENSE_ENDPOINT,{cache:"no-store"});if(!response.ok)throw new Error(`sense ${response.status}`);const snapshot=await response.json(),peak=clamp(Number(snapshot.audio_peak)||0,0,1);habitat.envelope=Math.max(peak,habitat.envelope*.84);habitat.beat=Math.max(0,peak-habitat.envelope*.72);habitat.audioPeak=peak;habitat.focused=mapFocusedRect(snapshot);habitat.available=Boolean(snapshot.supported);document.documentElement.style.setProperty("--audio-peak",String(peak));document.documentElement.dataset.music=peak>.035?"active":"quiet";if(habitat.focused){const key=`${habitat.focused.controlType}:${habitat.focused.name}:${Math.round(habitat.focused.x)}:${Math.round(habitat.focused.y)}`;if(key!==habitat.lastFocusedKey){habitat.lastFocusedKey=key;const owner=activeFae==="NYX"?"QIRA":activeFae;speak(owner,`PERCH // ${habitat.focused.controlType}${habitat.focused.name?` // ${habitat.focused.name}`:""}`);}}}catch{habitat.available=false;habitat.audioPeak*=.8;habitat.envelope*=.8;habitat.beat=0;habitat.focused=null;}}
function centroid(except=null){let x=0,y=0,count=0;for(const[fae,actor]of actors){if(fae===except||!assignedHere(fae))continue;x+=actor.x;y+=actor.y;count++;}return count?{x:x/count,y:y/count}:{x:innerWidth/2,y:innerHeight/2};}
function landmarkTarget(fae){const mark=habitat.focused;if(!mark||(fae!==activeFae&&fae!=="QIRA"))return null;const offsets=fae==="QIRA"?[Math.min(110,mark.width*.35+55),Math.min(80,mark.height*.25+32)]:[Math.min(95,mark.width*.28+42),-Math.min(92,mark.height*.35+38)];return{x:clamp(mark.x+offsets[0],62,innerWidth-62),y:clamp(mark.y+offsets[1],62,innerHeight-62),pull:fae===activeFae?.92:.56};}
function targetFor(fae,actor,now){const member=MEMBERS[fae],center={x:innerWidth/2,y:innerHeight/2},active=actors.get(activeFae)||actor,group=centroid(fae),cursorTarget=cursor.inside?cursor:center,phase=now*.00024*member.speed+actor.phase,perch=landmarkTarget(fae);if(perch&&(armyMode==="ROAM"||armyMode==="FLOCK"))return perch;if(armyMode==="REST"){const slots={KYU:[.18,.82],PAIMON:[.36,.88],LUMA:[.52,.84],SYLPH:[.70,.89],QIRA:[.84,.81],NYX:[.91,.18]};const[px,py]=slots[fae];return{x:innerWidth*px,y:innerHeight*py,pull:.55};}if(armyMode==="HUNT"){const pull=fae==="KYU"||fae==="SYLPH"?1:.54;return{x:cursorTarget.x+Math.cos(phase*3)*(50+ORDER.indexOf(fae)*15),y:cursorTarget.y+Math.sin(phase*2.7)*(42+ORDER.indexOf(fae)*11),pull};}if(armyMode==="FLOCK")return{x:active.x+Math.cos(phase+ORDER.indexOf(fae))*145,y:active.y+Math.sin(phase*1.2+ORDER.indexOf(fae))*105,pull:fae===activeFae?.20:.68};if(armyMode==="ORBIT"){const radius=110+ORDER.indexOf(fae)*32;return{x:cursorTarget.x+Math.cos(phase*5+ORDER.indexOf(fae))*radius,y:cursorTarget.y+Math.sin(phase*4.4+ORDER.indexOf(fae))*radius*.72,pull:.72};}if(armyMode==="SCATTER"){const dx=actor.x-cursorTarget.x,dy=actor.y-cursorTarget.y,mag=length(dx,dy);return{x:actor.x+(dx/mag)*420,y:actor.y+(dy/mag)*320,pull:1.1};}if(member.temperament==="CHASE"&&cursor.inside)return{x:cursor.x+Math.cos(phase*3.4)*120,y:cursor.y+Math.sin(phase*2.9)*85,pull:.42};if(member.temperament==="FORMATION")return{x:group.x+Math.cos(phase*2.2)*175,y:group.y+Math.sin(phase*1.8)*120,pull:.34};if(member.temperament==="PERCH")return{x:innerWidth*(.30+Math.sin(phase)*.09),y:innerHeight*(.74+Math.cos(phase*.7)*.08),pull:.24};if(member.temperament==="DART")return{x:innerWidth*(.5+Math.sin(phase*4.8)*.42),y:innerHeight*(.48+Math.cos(phase*3.9)*.38),pull:.58};if(member.temperament==="BOUNDARY")return{x:innerWidth*(.5+Math.sin(phase*1.4)*.34),y:innerHeight*(.50+Math.cos(phase*1.6)*.30),pull:.30};const oppositeX=cursor.inside?innerWidth-cursor.x:innerWidth*.82,oppositeY=cursor.inside?innerHeight-cursor.y:innerHeight*.23;return{x:oppositeX+Math.sin(phase)*90,y:oppositeY+Math.cos(phase*.8)*70,pull:.27};}
function applySeparation(fae,actor){let ax=0,ay=0;for(const[otherFae,other]of actors){if(otherFae===fae||!assignedHere(otherFae))continue;const dx=actor.x-other.x,dy=actor.y-other.y,dist=length(dx,dy);if(dist<125){const force=(125-dist)/125;ax+=(dx/dist)*force*90;ay+=(dy/dist)*force*90;}}return{ax,ay};}
function physics(now,dt){const margin=52;for(const[fae,actor]of actors){const node=spirits.get(fae),here=assignedHere(fae);if(node)node.style.display=here?"":"none";if(!here)continue;const member=MEMBERS[fae],target=targetFor(fae,actor,now);let ax=(target.x-actor.x)*.013*target.pull,ay=(target.y-actor.y)*.013*target.pull;const sep=applySeparation(fae,actor);ax+=sep.ax;ay+=sep.ay;const edgeForce=fae==="QIRA"?260:170;if(actor.x<margin)ax+=(margin-actor.x)*edgeForce/margin;if(actor.x>innerWidth-margin)ax-=(actor.x-(innerWidth-margin))*edgeForce/margin;if(actor.y<margin)ay+=(margin-actor.y)*edgeForce/margin;if(actor.y>innerHeight-margin)ay-=(actor.y-(innerHeight-margin))*edgeForce/margin;if(cursor.inside&&cursor.speed>650){const dx=actor.x-cursor.x,dy=actor.y-cursor.y,dist=length(dx,dy);if(dist<240){ax+=(dx/dist)*260;ay+=(dy/dist)*260;}}const peak=habitat.audioPeak,beat=habitat.beat;if(peak>.025){const music=(peak*55+beat*180)*member.reactivity;if(fae==="KYU"||fae==="SYLPH"){ax+=Math.sin(now*.015+actor.phase)*music;ay+=Math.cos(now*.012+actor.phase)*music*.72;}else if(fae==="LUMA")ay-=music*.22;else if(fae==="PAIMON")ax+=Math.sin(now*.006)*music*.30;}const noise=now*.001+actor.phase;ax+=Math.sin(noise*.73)*8*actor.energy;ay+=Math.cos(noise*.61)*7*actor.energy;actor.vx+=ax*dt;actor.vy+=ay*dt;const damping=armyMode==="REST"?.89:.965;actor.vx*=Math.pow(damping,dt*60);actor.vy*=Math.pow(damping,dt*60);const maxSpeed=90*member.speed*(armyMode==="SCATTER"?2:armyMode==="HUNT"?1.35:1)*(1+peak*.35),speed=length(actor.vx,actor.vy);if(speed>maxSpeed){actor.vx=actor.vx/speed*maxSpeed;actor.vy=actor.vy/speed*maxSpeed;}actor.x=clamp(actor.x+actor.vx*dt,24,innerWidth-24);actor.y=clamp(actor.y+actor.vy*dt,24,innerHeight-24);if(node){const tilt=clamp(actor.vx*.12,-14,14),musicScale=peak*.11*member.reactivity+beat*.18,scale=(fae===activeFae?1.10:.94+clamp(speed/500,0,.08))+musicScale;node.style.transform=`translate3d(${actor.x-56}px,${actor.y-56}px,0) rotate(${tilt}deg) scale(${scale})`;node.style.setProperty("--speed",String(clamp(speed/120,.2,1.8)));node.style.setProperty("--audio",String(peak));node.classList.toggle("active",fae===activeFae);node.classList.toggle("perched",Boolean(habitat.focused&&(fae===activeFae||fae==="QIRA")));node.classList.toggle("beat",beat>.12);}}}
function frame(now){const dt=clamp((now-lastFrame)/1000,.001,.034);lastFrame=now;if(surfaceActive)physics(now,dt);requestAnimationFrame(frame);}
function speak(fae,text){const node=spirits.get(fae);if(!node||!assignedHere(fae))return;const bubble=node.querySelector(".speech");bubble.textContent=String(text||"").slice(0,96);node.classList.remove("speaking");void node.offsetWidth;node.classList.add("speaking");}
function showWhisper(){const whisper=document.querySelector(".army-whisper");if(!whisper)return;const audio=Math.round(habitat.audioPeak*100),perch=habitat.focused?` // PERCH:${habitat.focused.controlType.toUpperCase()}`:"";whisper.textContent=`ARMY // ${armyMode} // SURFACE ${surfaceIndex+1}/${topology.surfaces} // AUDIO ${audio}%${perch}`;whisper.classList.add("show");setTimeout(()=>whisper.classList.remove("show"),1600);}
function setArmyMode(next,lockMs=0){if(!ARMY_MODES.includes(next))return;armyMode=next;if(lockMs)modeLockedUntil=Date.now()+lockMs;document.documentElement.dataset.armyMode=armyMode.toLowerCase();showWhisper();}
function summon(fae,message="",state=""){if(!MEMBERS[fae])return;activeFae=fae;activeMessage=message||`${fae} manifested.`;const requestedMode=modeFromState(state);if(requestedMode)setArmyMode(requestedMode,35000);const node=spirits.get(fae);if(node&&assignedHere(fae)){node.classList.remove("summoned");void node.offsetWidth;node.classList.add("summoned");speak(fae,activeMessage);}const actor=actors.get(fae);if(actor&&cursor.inside&&assignedHere(fae)){actor.vx+=(cursor.x-actor.x)*.42;actor.vy+=(cursor.y-actor.y)*.42;}const wave=document.querySelector(".summon-wave");if(wave){wave.style.setProperty("--member",MEMBERS[fae].color);wave.classList.remove("fire");void wave.offsetWidth;wave.classList.add("fire");}}
async function pullState(){try{const response=await fetch(STATE_ENDPOINT,{cache:"no-store"});if(!response.ok)return;const state=await response.json();if(MEMBERS[state.fae]){const requestedMode=modeFromState(state.state);if(requestedMode&&requestedMode!==armyMode)setArmyMode(requestedMode,35000);if(state.fae!==activeFae||(state.message&&state.message!==activeMessage))summon(state.fae,state.message||state.state||"Manifested",state.state);}}catch{}}
function ambientSpeech(){const local=ORDER.filter(assignedHere);if(!local.length)return;const fae=local[speechIndex++%local.length],member=MEMBERS[fae];speak(fae,member.stamps[(speechIndex+Math.floor(Date.now()/8000))%member.stamps.length]);}
function ambientDirector(){if(Date.now()<modeLockedUntil)return;const hour=new Date().getHours();if(hour>=23||hour<6)return setArmyMode("REST");const cycle=["ROAM","FLOCK","ROAM","ORBIT","ROAM"][Math.floor(Date.now()/45000)%5];setArmyMode(cycle);}
await listen("fairyos://haunt",({payload})=>{if(!payload||!MEMBERS[payload.fae])return;summon(payload.fae,payload.message||payload.state||"Manifested",payload.state);});
seedActors();await occupyMonitor();await refreshTopology();await senseCursor();await pullHabitatSense();setArmyMode("ROAM");requestAnimationFrame(frame);setInterval(senseCursor,90);setInterval(pullHabitatSense,180);setInterval(refreshTopology,10000);setInterval(occupyMonitor,20000);setInterval(ambientSpeech,9500);setInterval(ambientDirector,15000);setInterval(pullState,1800);addEventListener("resize",()=>{for(const actor of actors.values()){actor.x=clamp(actor.x,24,innerWidth-24);actor.y=clamp(actor.y,24,innerHeight-24);}});setTimeout(()=>summon("KYU","Office says stop being a widget. Habitat online.","ARMY_FLOCK"),650);
